language: python
python: 3.8
sudo: false
env:
  - TOXENV=py38-django22
  - TOXENV=py38-django30
  - TOXENV=docs
  - TOXENV=quality
install:
  - pip install -r requirements/ci.txt
script:
  - tox -e $TOXENV

