name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: [3.8]
        toxenv: [django20, django21, django111, docs, lint]

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install tox

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
